### ISSUE TITLE
centos 6.6

### ISSUE THREAD

**Issue by permalance** [fabiomaggio/mail-server-setup#1]
Hello, how to use this script into centos 6.6

**Comment by fabiomaggio** [comment]
Hi. I wrote this for a Debian installation but if you want to use this in Centos that should not be a big problem either. You just have to edit the OS specific commands. The best way to find them is by running the script and a couple of times and using the errors (if any) to refactor this script.

**Comment by permalance** [comment]
May i able to do this on centOS 6x? 

I did this but fail?

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    # build: .
    hostname: radeserver
    domainname: darkknowledge.net
    container_name: radeserver
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - ./config/:/tmp/docker-mailserver/

volumes:
  maildata:
    driver: local
```

[root@radeserver docker-mailserver]# docker-compose up -d radeserver
Creating network "dockermailserver_default" with the default driver
ERROR: 404 page not found
[root@radeserver docker-mailserver]# 

---

[root@radeserver docker-mailserver]# docker compose ps
docker: 'compose' is not a docker command.
See 'docker --help'.
[root@radeserver docker-mailserver]# 

I am using CentOS 6.8
